### ISSUE TITLE
question: reading terminated strings

### ISSUE THREAD

**Issue by retorquere** [dmendel/bindata#67]
I'm reading a format where strings are terminated by a comma or a semicolon rather than a null character. Is there a way to use read_until for this?

**Comment by dmendel** [comment]
Closed, same question as #68 .

**Comment by retorquere** [comment]
I have no problem with this being closed, but it's not the same question as 68 (even if the implementation of the two might be largely similar)

**Comment by dmendel** [comment]
Sorry, my mistake.

To be specific, BinData only has built in string primitives for fixed length and null terminated strings. These are general types common to many formats. Other string types are application specific with their own corner cases.

You can create your own primitive type to do this quite easily. Copy the code for `BinData::Stringz` and modify it to check for your desired terminator, rather than `"\0"`.

Remember to account for your specific corner cases:
* Should the terminator be included in the output?
* How do you encode a literal comma or semicolon in your string?
* What if no terminator is present?
* What about CR and LF?
